version: '3.7'
services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: SMA
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=SMADB
    ports:
      - "5432:5432"