version: "3.7"

services:
  backend:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"